ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectConfiguration__c/ApplicationConnectConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object is used for storing the configuration setting for Application Connect.</description>
    <label>ApplicationConnectConfiguration</label>
</CustomObject>

ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectConfiguration__c/fields/ApplicationDetailName__c.field-meta.xml
<CustomField>
    <fullName>ApplicationDetailName__c</fullName>
    <label>ApplicationDetailName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectConfiguration__c/fields/PermissionAccess__c.field-meta.xml
<CustomField>
    <fullName>PermissionAccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PermissionAccess</label>
    <type>Checkbox</type>
</CustomField>

ApplicatioAppexchageV1/force-app/main/default/classes/ApplicationConnectConfigurationSelector.cls
public with sharing class ApplicationConnectConfigurationSelector extends Aglib_SObjectSelector implements IApplicationConnectConfigurationSelector
{
	public static IApplicationConnectConfigurationSelector newInstance()
    {
        return (IApplicationConnectConfigurationSelector) ExternalApplicationConnect.SELECTOR.newInstance(ApplicationConnectConfiguration__c.SObjectType);
    } 

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			ApplicationConnectConfiguration__c.Id,
			ApplicationConnectConfiguration__c.ApplicationDetailName__c,
			ApplicationConnectConfiguration__c.PermissionAccess__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return ApplicationConnectConfiguration__c.SObjectType;
	}

    public ApplicationConnectConfiguration__c getApplicationConnectConfiguration(Id profileOrUserId)
    {
        ApplicationConnectConfiguration__c applicationConConfiguration = new ApplicationConnectConfiguration__c();

        try 
        {            
            applicationConConfiguration = ApplicationConnectConfiguration__c.getInstance(profileOrUserId);

            if(applicationConConfiguration.Name == null)
            {
                applicationConConfiguration = null;
            }
            return applicationConConfiguration;
        } 
        catch (Exception exp)
        {
            applicationConConfiguration = null;
            return applicationConConfiguration;
        }        
    }

}