ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectDetail__mdt/ApplicationConnectDetail__mdt.object-meta.xml
<CustomObject>
    <label>ApplicationConnectDetail</label>
    <pluralLabel>ApplicationConnectDetail</pluralLabel>
</CustomObject>

ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectDetail__mdt/fields/ApplicationType__c.field-meta.xml
<CustomField>
    <fullName>ApplicationType__c</fullName>
    <label>ApplicationType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sharepoint</fullName>
                <default>true</default>
                <label>Sharepoint</label>
            </value>
            <value>
                <fullName>AmazonS3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectDetail__mdt/fields/EndpointMethod__c.field-meta.xml
<CustomField>
    <fullName>EndpointMethod__c</fullName>
    <label>EndpointMethod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectDetail__mdt/fields/EndpointPath__c.field-meta.xml
<CustomField>
    <fullName>EndpointPath__c</fullName>
    <label>EndpointPath</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ApplicatioAppexchageV1/force-app/main/default/objects/ApplicationConnectDetail__mdt/fields/NamedCredentialName__c.field-meta.xml
<CustomField>
    <fullName>NamedCredentialName__c</fullName>
    <label>NamedCredentialName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ApplicatioAppexchageV1/force-app/main/default/classes/ApplicationConnectDetailSelector.cls
public with sharing class ApplicationConnectDetailSelector extends Aglib_SObjectSelector implements IApplicationConnectDetailSelector
{
	public static IApplicationConnectDetailSelector newInstance()
    {
        return (IApplicationConnectDetailSelector) ExternalApplicationConnect.SELECTOR.newInstance(ApplicationConnectDetail__mdt.SObjectType);
    } 

	public List<Schema.SObjectField> getSObjectFieldList()
	{
        //Id, ApplicationType__c, EndpointMethod__c, EndpointPath__c, NamedCredentialName__c
		return new List<Schema.SObjectField> {
			ApplicationConnectDetail__mdt.Id,
			ApplicationConnectDetail__mdt.ApplicationType__c,
			ApplicationConnectDetail__mdt.EndpointMethod__c,
            ApplicationConnectDetail__mdt.EndpointPath__c,
            ApplicationConnectDetail__mdt.NamedCredentialName__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return ApplicationConnectDetail__mdt.SObjectType;
	}

    public ApplicationConnectDetail__mdt getApplicationConnectDetails(String applicationConnectDetailName)
    {

        ApplicationConnectDetail__mdt appliactionConnectDetail = new ApplicationConnectDetail__mdt();

        try {
                if(Schema.sObjectType.ApplicationConnectDetail__mdt.isAccessible() == true)
                {
                    
                    appliactionConnectDetail = 
                        [
                        SELECT 
                            Id, ApplicationType__c, EndpointMethod__c, EndpointPath__c, NamedCredentialName__c
                        FROM
                            ApplicationConnectDetail__mdt
                        WHERE
                            DeveloperName =: applicationConnectDetailName
                        LIMIT 1
                        ];   
                }else
                {
                    appliactionConnectDetail = null;
                }
            return  appliactionConnectDetail;
        }
        catch (Exception exp) {
            return  appliactionConnectDetail;
        }
    }
}